### ISSUE TITLE
Production speed doesn't display anything after building construction

### ISSUE THREAD

**Issue by FallenFaust** [Xonoroff/Strategy#59]
**Description** 
Production speed doesn't display anything after building construction
![Screenshot_8](https://user-images.githubusercontent.com/60822173/81480320-b111ad80-9231-11ea-8bd7-e053a9add3f8.png)
**Steps**
1. Start a game with a clear player profile
2. Buy the first building
**Actual result**
It displays zero but building automatically produce currency
**Expected result**
Production speed should display production speed according to a building(s)

**Comment by Xonoroff** [comment]
In the production config for each building should be enabled next flag:
![image](https://user-images.githubusercontent.com/9823065/81494958-5fab0200-92b5-11ea-8b6b-ad307b2cb4ac.png)
